Improve clarity of `specularColor()` example
processing/p5.js pull request #5314
Opened 2021-06-15 00:44 UTC by JetStarBlues

The current example does not do the best job of showcasing `specularColor`. Since the colors of the pointlights are set to the same value as the specular color, it is not clear what the specular color adds to the scene. For example, if you comment out the lines with calls to `specularColor()`, the change the omission makes is not obvious.

_current_
![specularColorExample_current](https://user-images.githubusercontent.com/4354703/121975966-16db3d80-cd40-11eb-8b69-ed68e8023462.png)

_current with `specularColor` lines commented out_
![specularColorExample_current_commentedOut](https://user-images.githubusercontent.com/4354703/121975983-1c388800-cd40-11eb-923a-c67ca76fa0fd.png)

The example I have replaced it with aims to make the relationship more clear. Here is a [live version][0]. The light is given a white color, while the specular color is set to red. By clicking the mouse, you can toggle whether the specular color is set to red, or not set (and thus the default of white).

_change with red specular color_
![specularColorExample_proposal](https://user-images.githubusercontent.com/4354703/121975993-22c6ff80-cd40-11eb-8c53-0dfbc9464466.png)

_change with default specular color_
![specularColorExample_proposal_commentedOut](https://user-images.githubusercontent.com/4354703/121976001-26f31d00-cd40-11eb-8a34-17570a1a4254.png)

Change as docs:
![specularColorExample_proposal_docs](https://user-images.githubusercontent.com/4354703/121976026-31adb200-cd40-11eb-96f5-a560fd76922f.png)

[0]: https://editor.p5js.org/acedean/sketches/pTxAuDjfy

2021-07-28 15:02 UTC, stalgiag requested changes
two tiny comments

2021-07-28 15:02 UTC, stalgiag commented on src/webgl/light.js
> + *   if (setSpecularColor) {
maybe conditional should go under the pointlight call so that the comment above reads like the intro to a relevant chunk?

2021-07-28 15:02 UTC, stalgiag commented on src/webgl/light.js
> + * let setSpecularColor = true;
`setRedSpecular`? In simple examples it feels good to see as much info as possible about the impact of a boolean in its name.

2022-02-21 05:48 UTC, JetStarBlues commented
@stalgiag bumping this PR for review. Previously updated as per requested changes.

2022-02-21 14:04 UTC, stalgiag approved these changes

2022-02-21 14:05 UTC, merged