Translation to Turkish
processing/p5.js pull request #6159
Opened 2023-05-26 12:20 UTC by neondev27

Resolves #6158

 Changes:
Main READMEs are updated to contain Turkish translate access. 

 Screenshots of the change:
![pull request](https://github.com/processing/p5.js/assets/88967833/1a90e8a5-fd29-43eb-91a4-597029f96668)

![pr2](https://github.com/processing/p5.js/assets/88967833/7f88ccfb-c3ba-4a27-987c-7e9b68cc7a74)
![pr3](https://github.com/processing/p5.js/assets/88967833/2855f1be-ab29-4009-98c5-2eb709421192)
![pr4](https://github.com/processing/p5.js/assets/88967833/34cd9602-34ff-47e5-a8a8-fd5c45b41d64)

#### PR Checklist

- [x] Main markdown files translated in their new copies named in Turkish language

2023-06-06 20:48 UTC, osbm requested changes
Other than my comments on these files this is a very good translation. Thank you :)

2023-06-06 20:48 UTC, osbm commented on README.md
This link should not redirect to your own fork

2023-06-06 20:48 UTC, osbm commented on KATKIDABULUNMA.md
You should change the filename, filenames would be understandable to English speakers
For example like this:
CONTRIBUTING.tr.md

2023-06-06 20:48 UTC, osbm commented on DAVRANIS_KODU.md
You should change the filename, filenames should be understandable to English speakers
For example like this:
CODE_OF_CONDUCT.tr.md

2023-06-06 20:48 UTC, osbm commented on BENIOKU.md
You should change the filename, filenames should be understandable to English speakers
For example like this:
README.tr.md

2023-06-07 12:38 UTC, neondev27 commented
Done!

2023-06-09 06:24 UTC, Qianqianye commented
Thanks @neondev27 for translation the README.md file to Turkish and thanks @osbm for reviewing it. As I mentioned in the [comment](https://github.com/processing/p5.js/issues/6158#issuecomment-1584008039), we are rolling out new languages slowly to be absolutely sure that we can support the full translation and maintenance of each language. We'd like to come up with a system to manage different translation before we take in more translations as discussed in issue#[5208](https://github.com/processing/p5.js/issues/5208). Before the system is finalized, you can host the Turkish version of the main README.md and CODE_OF_CONDUCT_TR.md you translated on an external blog or site. And we can include the link to the external site on p5.js repos.

We do have an open issue#[4137](https://github.com/processing/p5.js/issues/4137) discussing the translation of the contributor docs. You can add a Turkish folder in the [contributor_docs](https://github.com/processing/p5.js/tree/main/contributor_docs) folder and add a Turkish translation of the this [README.md](https://github.com/processing/p5.js/tree/main/contributor_docs#readme) file, then we can add the Turkish tab on the [top nav bar](https://p5js.org/contributor-docs/#/).

I will close this PR for now. Please feel free to open a new PR if you'd like to add Turkish translation of the contributor docs. Thank you!

2023-06-09 06:24 UTC, closed without merging