try convert remaining to class
processing/p5.js pull request #6174
Opened 2023-05-31 15:41 UTC by wuyudi

record for #6172 

check which class triggers the problem.

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2023-05-31 16:05 UTC, wuyudi commented
test with `Renderer2D` caused the problem.

2023-06-29 16:40 UTC, davepagurek commented
Now that https://github.com/processing/p5.js/pull/6244 is merged, this could be fine. Worth pulling in the new changes and checking again maybe?

2023-06-29 19:14 UTC, wuyudi commented
I don't understand, why there is a timeout error in the test.

```
  1 failing
  1) src/webgl/material.js
       loadShader documentation
         example #1 works:
     Error: Timeout of 4000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

2023-06-30 05:29 UTC, wuyudi commented
In test, there is a bug.

```js
Renderer.prototype.textSize = function(s) {
```

works

```js
textSize (s) {
```

fails.

2023-06-30 05:45 UTC, wuyudi commented
Another bug:

```js
Renderer2D.prototype.text = function(str, x, y, maxWidth, maxHeight) { // pass
text(str, x, y, maxWidth, maxHeight) { // fail
```

2023-06-30 07:29 UTC, wuyudi commented
@davepagurek finished, with two more bugs bypassed.

2023-06-30 21:51 UTC, limzykenneth requested changes

2023-06-30 21:51 UTC, limzykenneth commented on src/core/p5.Renderer.js
> +    */
Just to note here as with p5.Element, these documentation should probably be left in the original location or it might not render correctly.

2023-07-01 19:15 UTC, limzykenneth commented on package.json
> +            "zh"
Just noticed this, were this meant to be changed and related to the class syntax for this PR?

2023-07-09 16:00 UTC, merged

2023-07-09 16:00 UTC, limzykenneth commented
Looks good. Thanks!