fix textbound invalid input
processing/p5.js pull request #6302
Opened 2023-07-27 07:32 UTC by adityagarg06

Resolves #6298 

 Changes:
Added an additional check for invalid input. Also I have written test for the same

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2023-07-27 10:14 UTC, limzykenneth requested changes

2023-07-27 10:14 UTC, limzykenneth commented on src/typography/p5.Font.js
> +    }
We don't usually handle incorrect parameter types this way as the FES is usually the one to take care of it. In terms of logic it should either do type coersion or return sensible default values, `null` is probably not useful in this case and can cause a property access error on the user's end.

2023-07-27 15:03 UTC, micuat commented
to me, coercion into string makes sense in case of a number. but then what if the input is an object, for example?

2023-09-04 04:19 UTC, munusshih commented
I think this should be handled in FES. Making an exception for this function might be a workaround for now, but doesn't seem to provide a general solution for this types of problem.

2023-09-05 19:55 UTC, Qianqianye commented
> I think this should be handled in FES. Making an exception for this function might be a workaround for now, but doesn't seem to provide a general solution for this types of problem.

Thanks @munusshih. I'm wondering what the GSoC FES contributor and mentors think about this @almchung @nbriz @Ayush23Dash

2023-09-08 09:06 UTC, Ayush23Dash commented
+1 to what @limzykenneth said. Returning a null is not a good solution. Moreover, this might solve the issue temporarily but we need to have a general solution rather than a customised one.

2024-11-10 12:59 UTC, dhowe commented
status ?

2024-11-10 14:08 UTC, limzykenneth commented
@dhowe I'll close this for now as the implemented solution is not necessarily what we needed.

2024-11-10 14:08 UTC, closed without merging