"add" korean translation of 'contributing_to_the_p5.js_reference.md
processing/p5.js pull request #6868
Opened 2024-03-15 10:48 UTC by wooknick

Changes:
contributing_to_the_p5.js_reference.md 파일 추가 및 번역

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

2024-03-15 10:51 UTC, wooknick commented
@yinhwa @designerSejinOH 

리뷰 부탁드립니다:)

2024-03-16 06:26 UTC, yinhwa commented
@wooknick 민욱님 초스피드 번역 넘 멋지고 감사드립니다 😎✨✨ 리뷰는 곧 진행하겠습니다!

2024-03-16 07:21 UTC, designerSejinOH commented
@wooknick 빠른 과제 수행 감사드립니다..!! 저도 곧 리뷰하겠습니다🥳

2024-03-16 08:16 UTC, yinhwa requested changes
@wooknick 민욱님의 문장력에 감탄하며 1차 리뷰 완료하였습니다! :) 빠른 리뷰 감사드려요! 이어서 @designerSejinOH 세진님이 2차 리뷰 진행할 예정입니다.

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +`@example` 태그 다음에는 HTML `<div>` 태그를 시작하고, 그 다음에 `<code>` 태그를 이어야 합니다. 그리고 열린 `<code>` 태그와 닫힌 `</code>` 태그 사이에, 예제 코드를 작성하면 됩니다. 좋은 예제 코드를 작성하기 위한 기본 원칙은 가능한 단순하고 작게 작성하는 겁니다. 예제는 의미가 있어야 하고, 기능이 어떻게
`<code>` 태그를 이어야 합니다.
->
`<code>` 태그가 뒤따라옵니다.

는 어떠실까요!

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +`@example` 태그 다음에는 HTML `<div>` 태그를 시작하고, 그 다음에 `<code>` 태그를 이어야 합니다. 그리고 열린 `<code>` 태그와 닫힌 `</code>` 태그 사이에, 예제 코드를 작성하면 됩니다. 좋은 예제 코드를 작성하기 위한 기본 원칙은 가능한 단순하고 작게 작성하는 겁니다. 예제는 의미가 있어야 하고, 기능이 어떻게
래핑 -> 래핑(wrapping)

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +만약, 예제 코드가 외부 에셋 파일을 사용해야 한다면, 필요한 파일들을 [/docs/yuidoc-p5-theme/assets](https://github.com/processing/p5.js/tree/main/docs/yuidoc-p5-theme/assets) 폴더에 넣어두세요(이미 해당 폴더에 존재하는 파일을 재사용해도 됩니다). 그리고 코드에서 "as
에셋 -> 애셋

참고: https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=266568&pageIndex=1

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +만약 속성이나 변수가 비공개(private) 함수이거나 비공개 변수라면 `@private` 태그를 쓸 수 있습니다. 어떤 기능에 `@private` 태그가 있다면, 그 기능은 웹사이트의 레퍼런스로 렌더링되지 않습니다. `@private` 태그를 사용하여 레퍼런스 주석 블록을 비공개(private)로 만드는 이유는 라이브러리 자체에 대한 내부 기능을 문서화
붙여쓰기

문서화 하기 -> 문서화하기

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +`@requires` 태그는 현재 모듈이 의존하고 있어, 반드시 가져와야(import) 하는 필수 모듈들을 정의합니다.
반드시 가져와야(import) 하는 -> 반드시 임포트되는(imported)

도 가능할것 같습니다!

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +p5.js 리포지터리는 p5.js 웹사이트를 빌드하고 실행하지 않아도 레퍼런스를 생성하고 미리 볼 수 있도록 설정되어 있습니다.
리포지터리 -> 리포지토리

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +이 과정을 통해 필요한 미리보기 파일들과 주요 `docs/reference/data.json` 파일이 생성됩니다. 이 파일은 웹 사이트에서 레퍼런스 페이지를 렌더링하는데 사용되는 것과 동일한 파일(경량화 후)입니다.
파일(경량화 후)
->
(경량화 후의) 파일

어떠실까요!

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +이 명령어는 변경사항이 생길때마다 레퍼런스 렌더링을 업데이트하는 실시간 미리보기(live preview) 기능을 시작합니다(변경 후에는 페이지를 새로고침 해야 변경 사항이 나타납니다). 이는 특히 브라우저에서 실행 중인 예제 코드를 미리 보는데 유용합니다.
새로고침 해야 -> 새로고침해야

2024-03-16 08:16 UTC, yinhwa commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +- 주요 템플릿 파일들은 `docs/` 폴더에 저장되어 있으며, 대부분의 경우 이 폴더 내의 파일들을 직접 변경해서는 안 됩니다. 단, `docs/yuidoc-p5-theme/assets` 폴더에 새로운 에셋 파일을 추가하는 경우에는 예외입니다.
안 됩니다. -> 안됩니다.
에셋 -> 애셋

2024-03-16 09:17 UTC, wooknick commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +@return {type} Description of the data returned.
> 116-119줄 코드 위치를 128번 줄로 옮겨야되는것 같습니다!

이 부분은 저도 조금 의견을 나눠보고 싶었는데요. 내용 흐름상 이게 더 자연스러운 것 같아 글의 순서를 임의로 변경한 부분입니다.

원문의 경우 매개변수 형식 설명 - 더 알아보기: 상수 - 반환 값 형식 설명 - 더 알아보기: 체이닝 순으로 내용이 작성되어 있는데요. 내용상 반환 값 형식 설명은 더 알아보기: 상수 에 이어진 설명이 아니고, 매개변수 형식 설명에서 이어지는게 더 자연스러워 보여서요.

그래도 원문의 순서를 따라가는게 맞을까요?

2024-03-16 09:25 UTC, wooknick commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +- `@param`은 함수가 받는 매개변수나 인자를 정의할 때 사용합니다.
> 인자(argument)를 영문병기할 필요가 있을지 고민되네요! 🤔

병기하는게 좋을 것 같아요. 그렇게 수정하겠습니다!

2024-03-16 09:38 UTC, wooknick commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +`@example` 태그 다음에는 HTML `<div>` 태그를 시작하고, 그 다음에 `<code>` 태그를 이어야 합니다. 그리고 열린 `<code>` 태그와 닫힌 `</code>` 태그 사이에, 예제 코드를 작성하면 됩니다. 좋은 예제 코드를 작성하기 위한 기본 원칙은 가능한 단순하고 작게 작성하는 겁니다. 예제는 의미가 있어야 하고, 기능이 어떻게
> `<code>` 태그를 이어야 합니다. -> `<code>` 태그가 뒤따라옵니다.
> 
> 는 어떠실까요!

그 앞부분도 부드럽게 이어지도록

`@example` 태그 다음에는 HTML `<div>` 태그가 시작되고, 그 다음에 `<code>` 태그가 뒤따라옵니다.

로 변경하겠습니다!

2024-03-16 09:48 UTC, wooknick commented
@yinhwa 님 감사합니다:) 리뷰해주신 내용 모두 확인했습니다. 리뷰 내용 중에 한 가지만 빼고 모두 반영하여 resolve 해두었고, 아직 반영하지 않은 부분은 해당 리뷰에 댓글로 의견을 남겨뒀습니다. 확인 부탁드립니다!

2024-03-18 08:40 UTC, designerSejinOH commented
@wooknick 수정사항 반영 감사드립니다..! 
@yinhwa 넵! 윤영님 2차리뷰 후 바로 민욱님 2차 리뷰로 넘어오겠습니다 :)

2024-03-18 15:20 UTC, designerSejinOH reviewed
@wooknick 2차 리뷰 완료하였습니다.! 문의하셨던 부분에 대해서만 코멘트 남겨놓았고 다른 부분들은 다 좋은 것 같습니다..! 민욱님께서 계속 읽어보시면서 이해하기 쉬운 문장으로 잘 다듬어주신 것 같아 처음 읽는 저도 편하게 읽을 수 있어서 좋았습니다 :) 
감사합니다! 고생하셨어요! 
코멘트 부분만 수정해서 올려주시면 Approve 진행하겠습니다 ☺️
(2차 리뷰 소요 시간: 2024.03.18 23:30-24:20, 50분)

2024-03-18 15:20 UTC, designerSejinOH commented on contributor_docs/ko/contributing_to_the_p5.js_reference.md
> +@return {type} Description of the data returned.
더 알아보기: 상수 가 매개변수 형식에 이어진 추가적인 매개변수 형태에 대한 설명이라 원문에서 매개변수 형식 설명 - 더 알아보기: 상수 - 반환 값 형식 설명 순으로 되어있는 것 같아요..! 원문의 의도는 함수의 주석 중 메소드, 파람, 리턴 순으로 설명하는데 더 알아보기:  상수가 파람에 대한 부연 설명의 의도인 것 같네요.. 

- 주석의 구조
   - 메소드, 파람, 리턴
- 파람의 일반적인 주석 방법 
   - 파람의 constant 주석 방식
- 리턴 주석 방법

요런 구조인 것 같아요. 원문에서 매개변수에 대한 부연 설명인 더 알아보기 : 상수에 괜히 헤딩 마크업을 넣어서 완전히 다른 내용인 것처럼 혼동을 준 것 같네요..ㅜ 우선 원문 순으로 다시 원복시켜주시면 감사하겠습니다.. 🥹

2024-03-18 16:14 UTC, wooknick commented
@designerSejinOH 
리뷰 감사합니다! 의견 주신대로 원문의 순서와 일치하도록 수정했습니다.

@yinhwa 
1차 리뷰해주신 내용 반영하고 나서 제가 인화님에게 리뷰를 re-request 한 것 같은데, 그래서인지 인화님 리뷰가 다시 awaiting으로 뜹니다.😅 이 부분 한 번만 확인 부탁드리겠습니다.

2024-03-19 02:15 UTC, designerSejinOH approved these changes
Hi @qianqianye @limzykenneth, we have approved this PR!
We're ready to merge ☺️

2024-03-19 05:09 UTC, merged

2024-03-19 05:13 UTC, Qianqianye commented
Looks great, thanks @wooknick @designerSejinOH @yinhwa! 💗
@all-contributors please add @wooknick for translation