Create contributing_to_the_p5.js_reference.md
processing/p5.js pull request #6869
Opened 2024-03-15 12:09 UTC by asukaminato0721

Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2024-03-17 05:24 UTC, unicar9 reviewed
well done!

2024-03-17 05:24 UTC, unicar9 commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +这将启动一个渲染参考文献的实时预览，每次您进行更改时都会更新（您需要在进行更改后刷新页面才能看到它们）。这是有用的，特别是用于预览在浏览器中运行的示例代码。
这是有用的，特别是用于预览在浏览器中运行的示例代码。-> 对于在浏览器中预览示例代码来说，这特别有用。

2024-03-17 05:24 UTC, unicar9 commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +- 主要的模板文件存储在 `docs/` 文件夹中，在大多数情况下，您不应直接更改此文件夹中的文件，除非是要在 `docs/yuidoc-p5-theme/assets` 文件夹中添加新的资产文件。
资产文件。-> 文件 即可。已经说了路径是 `docs/yuidoc-p5-theme/assets`，assets files 翻译成 资产文件 反而有点让人疑惑。

2024-03-17 05:24 UTC, unicar9 commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +- 为了持续对参考文献进行工作，您可以运行以下命令。
为了持续对参考文献进行工作，您可以运行以下命令。-> 为了持续修改完善参考文献，您可以运行以下命令。（更符合中文习惯）

2024-03-17 05:24 UTC, unicar9 commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +通过以上方法，您应该拥有编写和编辑 p5.js 参考注释所需的大部分工具。然而，还有一些 JSDoc 样式参考注释的更多专门用法，您可能会在 p5.js 中遇到。这些在某些情况下很有用，但通常不是您经常需要的东西。
通过以上方法，您应该拥有编写和编辑 p5.js 参考注释所需的大部分工具。-> 以上就是您编写和编辑 p5.js 参考注释的大多数方法。（tools 在此为方法的意思）

2024-03-17 05:24 UTC, unicar9 commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +如果您的示例使用外部资产文件，请将它们放入 [/docs/yuidoc-p5-theme/assets](https://github.com/processing/p5.js/tree/main/docs/yuidoc-p5-theme/assets) 文件夹中（或者重用其中已有的文件），然后在代码中使用 "assets/filename.ext" 链接到它们。请参阅 [tint()](htt
external asset files 我倾向于翻译成 外部素材文件，更好理解

2024-03-17 05:24 UTC, unicar9 commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +如果两个签名之间唯一的区别是添加了一个可选参数，则不必创建单独的签名。如果可能的话，请限制使用此功能，因为它可能会在参考文献中创建不必要的噪音。
minor: 创建不必要的噪音 -> 制造不必要的噪音

2024-03-17 17:31 UTC, sproutleaf requested changes
谢谢！

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +这种形式的代码块中的任何内容都将被解释为参考文献。您可能通过 [JSDoc](https://jsdoc.app/) 熟悉了这种样式的代码注释。虽然 p5.js 不使用 JSDoc，但它使用了一个非常相似的工具，叫做 [YUIDoc](https://yui.github.io/yuidoc/)，它具有非常相似的参考语法。在这种参考注释样式中，每个注释块进一步分成各个元素，我们将在下面看一下。
熟悉了 -> 已熟悉？

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +在注释的顶部是函数的文本描述。此描述可以包含 markdown 语法和 HTML。描述应该简洁明了，描述函数的功能，并在必要时描述一些有关其怪癖或行为的细节。
怪癖或行为的细节 -> 性能或反常行为的细节

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +如果两个签名之间唯一的区别是添加了一个可选参数，则不必创建单独的签名。如果可能的话，请限制使用此功能，因为它可能会在参考文献中制造不必要的噪音。
噪音 -> 干扰信息或相似信息

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +块的开始包含变量的描述（在这种情况下是 `mouseX`）。为了定义变量的名称，我们使用 `@property` 而不是 `@method`。`@property` 的语法与 `@param` 类似，用于定义类型及其名称。`@readonly` 标签在大多数 p5.js 变量上都存在，并且用于内部指示该值不应由库用户直接覆盖。
在这种情况下 -> 在该例子中

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +块的开始包含变量的描述（在这种情况下是 `mouseX`）。为了定义变量的名称，我们使用 `@property` 而不是 `@method`。`@property` 的语法与 `@param` 类似，用于定义类型及其名称。`@readonly` 标签在大多数 p5.js 变量上都存在，并且用于内部指示该值不应由库用户直接覆盖。
`@readonly` 标签在大多数 p5.js 变量上都存在，并且用于内部指示该值不应由库用户直接覆盖。 -> 大多数 p5.js 变量都带有`@readonly`标签，用于内部指示该值不应由库用户直接覆盖。

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +`sin()` 和 `mouseX` 的参考注释中，都存在的一个标签是 `@example` 标签，我们还没有讨论过。这个标签是您定义访问参考页面时运行的代码示例的地方。
`sin()` 和 `mouseX` 的参考注释中，都存在的一个标签是 `@example` 标签，我们还没有讨论过。 -> `sin()` 和 `mouseX` 的参考注释中，都有一个我们还没有讨论过的 `@example` 标签。

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +![Screenshot of the p5.js reference page of the "red()" function, showing only the example code section.](images/reference-screenshot.png)
link最开始漏了../

2024-03-17 17:31 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +有关 `describe()` 的更多信息，请访问 [Web 无障碍贡献者文档](https://p5js.org/contributor-docs/#/web_accessibility?id=user-generated-accessible-canvas-descriptions)。
这里的web需要保留英文吗？

2024-03-18 09:46 UTC, unicar9 approved these changes

2024-03-18 13:57 UTC, sproutleaf commented on contributor_docs/zh/contributing_to_the_p5.js_reference.md
> +![Screenshot of the p5.js reference page of the "red()" function, showing only the example code section.](../images/reference-screenshot.png)
诶，我不知道为什么在这里用../images/的link render不了，但是在nancy的PR里是可以的。

asuka，麻烦改了码以后preview一下page看哪个link可以render出图！谢谢！

2024-03-18 14:01 UTC, sproutleaf approved these changes
Both @unicar9 and I have approved this PR. Tagging @Qianqianye and @limzykenneth , thank you!

2024-03-18 17:58 UTC, merged

2024-03-18 17:58 UTC, Qianqianye commented
Looks great! Thanks @asukaminato0721 @unicar9 @sproutleaf!