Create webgl_contribution_guide.md
processing/p5.js pull request #6878
Opened 2024-03-16 19:37 UTC by Harrycheng233

Resolves #[[webgl_contribution_guide.md](https://github.com/processing/p5.js/commit/9f6be0438a853b02d070fe333e12ce4864ebdb17)]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2024-03-17 07:07 UTC, unicar9 reviewed
Well done!

2024-03-17 17:48 UTC, sproutleaf requested changes
翻译得很好，谢谢+辛苦了！

2024-03-17 17:48 UTC, sproutleaf commented on contributor_docs/zh/webgl_contribution_guide.md
> +- 阅读我们的 [p5.js WebGL architecture overview](webgl_mode_architecture.md) 了解 WebGL 模式与 2D 模式的区别。这将是理解着色器、笔触等一些实现细节的宝贵参考。
中英文文档不在一个文件夹中，所以本地链接有一些小区别。

这里的`[p5.js WebGL architecture overview](webgl_mode_architecture.md)` 应该是 `[p5.js WebGL architecture overview](../webgl_mode_architecture.md)`

2024-03-17 17:48 UTC, sproutleaf commented on contributor_docs/zh/webgl_contribution_guide.md
> +  我们通过 [in a GitHub Project](https://github.com/orgs/processing/projects/5) 来组织问题，并将它们分为以下几类：
[in a GitHub Project]可以改成[GitHub Project]

2024-03-17 17:48 UTC, sproutleaf commented on contributor_docs/zh/webgl_contribution_guide.md
> +- **尚无解决方案的bugs (Bugs with no solution yet)** 是指那些还需要通过调试来确定具体原因的错误报告。在确定具体原因之前，这些bug还不适合进行修复；一旦原因明确，我们便可以开始讨论最佳的修复方法。
asking for opinions: bug要翻成中文吗？

2024-03-17 17:48 UTC, sproutleaf commented on contributor_docs/zh/webgl_contribution_guide.md
> +- **在任何情况下都无法正常运作的功能 (Features that don't work in all contexts)** 是指在WebGL模式下存在但并不适用于所有WebGL使用场景的功能。举例来说，某些p5.js方法同时支持2D和3D坐标系统，但在使用3D坐标时，有些方法可能会失效。在通常情况下，这些功能是可以着手进行开发的。
Features that don't work in all contexts这里应该是“无法在所有情况下正常运作的功能”

举例来说，某些p5.js方法同时支持2D和3D坐标系统，但在使用3D坐标时，有些方法可能会失效。 -> 举例来说，某些p5.js方法同时支持2D和3D坐标系统，然而其他的方法可能在使用3D坐标时失效。

2024-03-17 17:48 UTC, sproutleaf commented on contributor_docs/zh/webgl_contribution_guide.md
> +- **功能请求 (Feature requests)** 是指对所有其他代码的更改请求；这些请求还需要一些讨论，以确保它们符合WebGL模式下的发展方向。
对所有其他代码的更改请求 -> 其他所有的代码更改请求

2024-03-17 17:48 UTC, sproutleaf commented on contributor_docs/zh/webgl_contribution_guide.md
> +如果一个功能只适用于WebGL，而不是将像素与2D模式中的进行比较，通常的方法是检查其中的几个像素，以确保它们的颜色符合我们的预期。在不久的将来，我们可能会将其改进为一个更加强劲且稳定的系统，并且该系统会与我们期望结果的完整图像快照进行比较，而非其中的几个像素。但在现有情况下，以下是一个像素颜色检查的示例：
而不是将像素与2D模式中的进行比较，通常的方法是检查其中的几个像素，以确保它们的颜色符合我们的预期。-> 我们通常会检查其中的几个像素，而不是将像素与2D模式的结果进行比较，以确保它们的颜色符合我们的预期。

2024-03-17 17:48 UTC, sproutleaf commented on contributor_docs/zh/webgl_contribution_guide.md
> +尽管性能不是p5.js的首要关注点，但我们仍会尽量确保修改不会对性能造成较大影响。在通常情况下，我们会创建两个测试绘图：一个是包含了你的修改，而另一个则没有。然后，我们会比较两者的帧率。
一个是包含了你的修改，而另一个则没有。 -> 一个包含了你的修改，另一个则没有。

2024-03-18 20:56 UTC, Harrycheng233 commented on contributor_docs/zh/webgl_contribution_guide.md
> +- **尚无解决方案的bugs (Bugs with no solution yet)** 是指那些还需要通过调试来确定具体原因的错误报告。在确定具体原因之前，这些bug还不适合进行修复；一旦原因明确，我们便可以开始讨论最佳的修复方法。
我想“漏洞”和“错误”都可以用来refer "bug", 所以保持原文可以保持一致性

2024-03-18 21:19 UTC, sproutleaf approved these changes
谢谢Harry!

2024-03-19 01:44 UTC, unicar9 approved these changes
谢谢！

2024-03-19 01:46 UTC, unicar9 commented
Hi @Qianqianye and @limzykenneth, this PR is ready to merge, thanks :)

2024-03-19 05:16 UTC, Qianqianye commented
Looks great, thanks @Harrycheng233 @sproutleaf @unicar9  💗
@all-contributors please add @Harrycheng233 for translation

2024-03-19 05:16 UTC, merged