Update steward_guidelines.md
processing/p5.js pull request #6879
Opened 2024-03-16 21:11 UTC by Harrycheng233

edit the text after "#### test Task".

Resolves #[Add issue number here]

 Changes:
 
Edited the text after "#### test Task"

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2024-03-17 07:21 UTC, unicar9 commented on contributor_docs/zh/steward_guidelines.md
> +根据你的工作内容，选择最简化的watch任务可以节省手动重新构建的时间。
虽然我对您->你的改动没有什么意见，但是之前有同学一直使用您，我们是否可以保持一致？

2024-03-17 07:21 UTC, unicar9 commented on contributor_docs/zh/steward_guidelines.md
> +有时，需要审核的问题和PR的数量可能会变得有些压倒性，尽管我们尽力采取一些简化流程的措施，但以下是你可以利用的一些提示和技巧，以帮助你审核问题和PR。
有时，需要审核的问题和PR的数量可能会变得有些压倒性，尽管我们尽力采取一些简化流程的措施，但以下是你可以利用的一些提示和技巧，以帮助你审核问题和PR。-> 有时，需要审核的问题和 PR 的数量可能会让人手足无措。我们已经尽力采取措施来简化流程，与此同时，您也可以利用一些技巧和窍门来帮助审查问题和 PR。

2024-03-17 19:48 UTC, sproutleaf requested changes
谢谢！

2024-03-17 19:48 UTC, sproutleaf commented on contributor_docs/zh/steward_guidelines.md
> +在browserify步骤中，除了将各种文件合并为一个文件外，还执行了其他几个步骤。首先，使用`brfs-babel`将`fs.readFileSync()`节点.js特定代码的使用替换为文件的实际内容。这主要用于WebGL代码，以将作为独立文件编写的着色器代码内联到源代码中。
节点.js 保留英文原名 Node.js

2024-03-17 19:48 UTC, sproutleaf commented on contributor_docs/zh/steward_guidelines.md
>  在捆绑之后但将捆绑代码写入文件之前，如果不打算缩小代码，则通过`pretty-fast`进行清理，以使最终格式更加一致（我们预计可以阅读和检查p5.js源代码，如果需要的话）。
原文：After bundling but before the bundled code is written to file, the code is passed through pretty-fast, if it is not meant to be minified, it should be cleaned up so the final formatting is a bit more consistent (we anticipate the p5.js source code can be read and inspected if desired).

因为原文里逗号的使用，导致中英之间逻辑有些许误差。supposed to be along the lines of：在捆绑之后但将捆绑代码写入文件之前，代码会在pretty-fast中运行。如果代码不应被缩小，我们则需清理代码，以使最终格式更加一致。（如果有需要的话，p5.js 源代码应保持可读、可查阅）

2024-03-17 19:48 UTC, sproutleaf commented on contributor_docs/zh/steward_guidelines.md
>  此任务将运行上述描述的文档和库构建，然后启动一个Web服务器，提供与网站上[http://localhost:9001/docs/reference/](http://localhost:9001/docs/reference/)上的参考页面功能相似的版本。然后，它将监视源代码的更改，并重新构建文档和库。
这里的Web不是特有名词，可以翻译成网站

提供与网站上http://localhost:9001/docs/reference/上的参考页面功能相似的版本 -> 这句话link前后有两个重复的上

2024-03-17 19:48 UTC, sproutleaf commented on contributor_docs/zh/steward_guidelines.md
> +watch任务将监视一系列文件的更改，并根据所更改的文件运行相关任务以构建参考文档或库。这些任务的作用是相同的，唯一的区别在于范围。
可以把监视改成观察，这样听起来温和一些

2024-03-17 19:48 UTC, sproutleaf commented on contributor_docs/zh/steward_guidelines.md
> +当你在内联文档中工作时，这很有用，因为您无需每次更改时将构建文件从p5.js存储库移动到本地的p5.js-website存储库并重新构建网站，而是可以在浏览器中预览你的更改，这个参考版本稍微简化了一些。这样，你可以更有信心地认为你所做的更改会在网站上正确显示。请注意，这仅适用于对内联文档的修改；对参考页面本身（包括样式和布局）的更改，应在网站存储库上进行修改和测试。
可以说明这很有用的这值的是什么。原文里写的是`grunt` `yui:dev` is useful when you are working on the reference...

2024-03-17 19:48 UTC, sproutleaf commented on contributor_docs/zh/steward_guidelines.md
> +有时，需要审核的问题和PR的数量可能会变得有些压倒性，尽管我们尽力采取一些简化流程的措施，但以下是你可以利用的一些提示和技巧，以帮助你审核问题和PR。
我的建议：

有时，需要审核的问题和PR的数量可能会变得有些压倒性，尽管我们尽力采取一些简化流程的措施，但以下是您可以利用的一些提示和技巧，以帮助审查问题和 PR。 -> 有时，需要审核的问题和PR的数量太多，另人应接不暇。我们尽力推行简化流程的措施之余，以下有一些您可以使用的提示和技巧，让审查问题和 PR 更为简便。

2024-03-17 19:48 UTC, sproutleaf commented on contributor_docs/zh/steward_guidelines.md
> +![Cropped screenshot of the top right corner of a GitHub repository page showing a series of buttons in the center from left to right: Sponsor, Watch, Fork, Starred.](images/github-repo-metrics.png)
这里图片链接是错的，请改正

2024-03-19 02:35 UTC, asukaminato0721 commented on contributor_docs/zh/steward_guidelines.md
> +![Cropped screenshot of the top right corner of a GitHub repository page showing a series of buttons in the center from left to right: Sponsor, Watch, Fork, Starred.](images/github-repo-metrics.png)
try `(../images/github-repo-metrics.png)`

2024-03-19 02:36 UTC, asukaminato0721 commented on contributor_docs/zh/steward_guidelines.md
> +![Cropped screenshot of the top right corner of a GitHub repository page showing a series of buttons in the center from left to right: Sponsor, Watch, Fork, Starred.](images/github-repo-metrics.png)
ref https://github.com/processing/p5.js/pull/6869/files#diff-71e981d649c16da7e769095919eab0a97cac57c546be9479b16b96d484053c52R203

2024-03-19 09:32 UTC, unicar9 commented on contributor_docs/zh/steward_guidelines.md
>  Gruntfile.js文件包含了p5.js及其他内容的主要构建定义。构建库和文档所使用的不同工具包括但不限于Grunt、Browserify、YUIDoc、ESLint、Babel、Uglify和Mocha。从`default`任务开始，逆向分析可能会有所帮助。
之前译文没有遵循中英文混排在英文前后加空格的板式，请再通读一遍修改一下哈~

2024-03-19 09:33 UTC, unicar9 commented on contributor_docs/zh/steward_guidelines.md
> +根据你的工作方式设置这些通知，可以避免手动查找相关 issues /PR 并避免被 GitHub 的无休止的通知淹没。在这里需要保持良好的平衡。作为起始建议，你可以关注该存储库的“Issues”和“Pull Requests”，并设置仅在“参与、提及和自定义”时接收电子邮件通知。
另外中文引号“”和英文""有区别，请用对应的引号哈

2024-03-19 21:30 UTC, sproutleaf approved these changes
谢谢+辛苦了！

2024-03-19 23:42 UTC, unicar9 approved these changes

2024-03-19 23:43 UTC, unicar9 commented
Hi @Qianqianye and @limzykenneth, this PR can be merged, thanks :)

2024-03-19 23:54 UTC, Qianqianye commented on contributor_docs/zh/steward_guidelines.md
> +无论你是刚加入我们作为管理员、还是 p5.js 经验丰富的维护者，或者介于两者之间，本指南包含了许多信息、技巧和诀窍，将帮助你和其他贡献者有效地为 p5.js 做出贡献。除非另有说明，这里所写的大部分内容都是指南，这意味着你可以根据自己的工作流程来适应这里所指示的做法。
How about '无论你是刚加入我们的管理员'?
@unicar9 @sproutleaf @Harrycheng233

2024-03-20 21:02 UTC, unicar9 commented on contributor_docs/zh/steward_guidelines.md
> +无论你是刚加入我们作为管理员、还是 p5.js 经验丰富的维护者，或者介于两者之间，本指南包含了许多信息、技巧和诀窍，将帮助你和其他贡献者有效地为 p5.js 做出贡献。除非另有说明，这里所写的大部分内容都是指南，这意味着你可以根据自己的工作流程来适应这里所指示的做法。
@Qianqianye：@Harrycheng233 已修改好：）

2024-03-20 21:04 UTC, merged

2024-03-20 21:05 UTC, Qianqianye commented
Thanks @Harrycheng233 @unicar9 @sproutleaf 💓