Contributor guidelines part2
processing/p5.js pull request #6880
Opened 2024-03-17 00:57 UTC by Tmicrd

Resolves #[Add issue number here]

 Changes:

Updated the file `contributor_guidelines.md` by adding Chinese translation, starting from `## 代码库拆分`.

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2024-03-17 10:08 UTC, unicar9 reviewed
Nice job!

2024-03-17 10:08 UTC, unicar9 commented on contributor_docs/zh/contributor_guidelines.md
>      npm test
无需空格

2024-03-17 11:01 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +首先，下载并安装 [GitHub 桌面版](https://desktop.github.com/)。安装成功后，打开应用程序。根据提示登录你的 GitHub 账户。登录成功后，你可以看到你的项目，包括你 fork 的 p5.js。选择名为：`你的用户名/p5.js` 的项目，然后点击蓝色 “克隆” 按钮。根据提示选择项目存储位置，你可以更改存储位置也可以保留默认选项并继续。
完成

2024-03-17 11:06 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +克隆成功后，你需要选择使用该 fork 的目的。请选择 “贡献到父项目”，然后点击 “继续”。
> 页面中的按钮无需翻译哈。

完成

2024-03-17 11:08 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +克隆成功后，你需要选择使用该 fork 的目的。请选择 “贡献到父项目”，然后点击 “继续”。
> 检查一下原文中的图片是否复制到译文中，图片链接无需翻译。
> 
> ![The GitHub Desktop user interface after signing in. On the right half of the screen, it lists your projects, and a Clone button in the bottom right.](images/github-desktop-init.png)

完成

2024-03-17 11:09 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +
> 图片是否复制了？

完成

2024-03-17 11:09 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +## 拆分代码库
> 拆分代码库 -> 代码库拆解（名词更符合意思）

完成

2024-03-17 11:11 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +   ```
> 前面无需空格

完成

2024-03-17 11:12 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +
> 此处有图片

完成

2024-03-17 11:14 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +如果你要进行单元测试，请参阅[这里](./unit_testing.md)。需要注意的是，PR 中应该包含功能强化、功能新增和错误修复的单元测试。
> 需要注意的是，PR 中应该包含功能强化、功能新增和错误修复的单元测试。-> 需要注意的是，对于任何功能强化、功能新增和错误修复，都应该在 PR 中添加相关的单元测试。

完成

2024-03-17 11:14 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
>  ### 可访问性
> 无障碍

完成

2024-03-17 11:15 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
>      npm test
> 无需空格

完成

2024-03-17 11:21 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +- `src` - 存放最终生成的 `p5.js` 和 `p5.min.js` 文件的位置
> 存放最终生成的 `p5.js` 和 `p5.min.js` 文件的位置 -> 最终生成 `p5.js` 和 `p5.min.js` 文件的所有代码都存放于此。

完成

2024-03-17 11:22 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +
> 图片？

完成

2024-03-17 11:23 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> 此处也有图片

完成

2024-03-17 19:52 UTC, sproutleaf requested changes
可不可以不要复制图片，直接改internal link就好？我觉得同样的图，一个repo里面有一份就够了，复制图片的话一会导致不必要的资料重复、二会使得文档和文档之间标准不同。

2024-03-18 02:29 UTC, Tmicrd commented
> 可不可以不要复制图片，直接改internal link就好？我觉得同样的图，一个repo里面有一份就够了，复制图片的话一会导致不必要的资料重复、二会使得文档和文档之间标准不同。

已完成。

2024-03-18 14:22 UTC, sproutleaf requested changes
写得很好，辛苦了，谢谢！

2024-03-18 14:22 UTC, sproutleaf commented on contributor_docs/zh/contributor_guidelines.md
> +git commit -m "给 circle() 函数添加文档示例"
这里的git message不用翻译，因为在实际操作中，我们是希望和修改代码有关的git command都能用英文的。不然不会中文的贡献者读不懂。

2024-03-18 14:22 UTC, sproutleaf commented on contributor_docs/zh/contributor_guidelines.md
> +p5.js 的代码规范或者代码风格由 ESLint 执行。任何 git 提交和拉取请求在被接受之前，都必须通过 ESLint 代码检查。要遵循正确的代码规范，最简单方法是在文本编辑器中使用可用的 ESLint 插件，它可以高亮显示 ESLint 检查到的错误（适用于大多数流行的文本编辑器）。
这里的ESLint漏了一个链接。https://eslint.org/

2024-03-18 14:22 UTC, sproutleaf commented on contributor_docs/zh/contributor_guidelines.md
> +- **可访问性**：我们将可访问性置于首位，在做决定时，必须考虑如何提升历史上被边缘化的群体的可访问性。在我们的访问声明中可以了解更多相关信息。
访问声明 -> 无障碍报告

2024-03-18 14:22 UTC, sproutleaf commented on contributor_docs/zh/contributor_guidelines.md
> +- **初学者友好**：p5.js API 旨在对初学者友好，它使用前沿的 HTML5/Canvas/DOM API ，为创建交互性视觉内容提供了低门槛。
初学者友好 -> 适合初学者

2024-03-19 01:57 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +git commit -m "给 circle() 函数添加文档示例"
> 这里的git message不用翻译，因为在实际操作中，我们是希望和修改代码有关的git command都能用英文的。不然不会中文的贡献者读不懂。

完成

2024-03-19 01:58 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +p5.js 的代码规范或者代码风格由 ESLint 执行。任何 git 提交和拉取请求在被接受之前，都必须通过 ESLint 代码检查。要遵循正确的代码规范，最简单方法是在文本编辑器中使用可用的 ESLint 插件，它可以高亮显示 ESLint 检查到的错误（适用于大多数流行的文本编辑器）。
> 这里的ESLint漏了一个链接。https://eslint.org/

完成

2024-03-19 01:59 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +- **可访问性**：我们将可访问性置于首位，在做决定时，必须考虑如何提升历史上被边缘化的群体的可访问性。在我们的访问声明中可以了解更多相关信息。
> 无障碍报告

完成

2024-03-19 01:59 UTC, Tmicrd commented on contributor_docs/zh/contributor_guidelines.md
> +- **初学者友好**：p5.js API 旨在对初学者友好，它使用前沿的 HTML5/Canvas/DOM API ，为创建交互性视觉内容提供了低门槛。
> 适合初学者

完成

2024-03-19 09:37 UTC, closed without merging