Hindi translation of webgl contribution guide
processing/p5.js pull request #6886
Opened 2024-03-18 13:05 UTC by ranaaditya

Resolves Hindi Translation of WebGL Contribution Guide

 Changes: **Add webgl_contribution_guide.md in contributor_docs/hi/ folder**

 Screenshots of the change:

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2024-03-18 13:07 UTC, ranaaditya commented
@TanviKumar @Divyansh013 can you please review this PR and let me know the changes if any.

Thanks !

2024-03-19 14:02 UTC, Divyansh013 requested changes
Hey @ranaaditya have left some reviews please look into that. Thanks for your PR :)

2024-03-19 23:13 UTC, ranaaditya commented on contributor_docs/hi/webgl_contribution_guide.md
> +- हमारे [योगदानकर्ता दिशानिर्देश](https://p5js.org/contributor-docs/#/./contributor_guidelines) पढ़ें जिससे यह पता चलेगा कि मुद्दों को कैसे बनाया जाए, कोडबेस को कैसे सेट किया जाए और परिवर्तनों को कैस
resolved :+1:

2024-03-19 23:18 UTC, ranaaditya commented on contributor_docs/hi/webgl_contribution_guide.md
> +- यह जानना भी उपयोगी हो सकता है कि ब्राउज़र के वेबजीएल एपीआई के बारे में थोड़ा जानना, जिस पर पी5.जेएस का वेबजीएल मोड बनाया गया है:
resolved :+1:

2024-03-19 23:26 UTC, ranaaditya commented
Hi @Divyansh013 I have fixed the suggested changes, can you review and let me know if something needs to be fixed in it.

Thanks,
Aditya

2024-03-20 14:22 UTC, Divyansh013 approved these changes

2024-03-20 18:58 UTC, Qianqianye commented
Thanks @ranaaditya for translating and @Divyansh013 for reviewing. I will merge it after @TanviKumar approves the translation since all the translations need to be approved by 2 translation stewards. Thanks!

2024-03-21 08:01 UTC, TanviKumar approved these changes

2024-03-21 14:06 UTC, TanviKumar commented
@Qianqianye this PR can be merged

2024-03-21 17:56 UTC, merged

2024-03-21 17:57 UTC, Qianqianye commented
Looks great, thanks @ranaaditya @Divyansh013 @TanviKumar  💗
@all-contributors please add @ranaaditya for translation