hindi translation - contributing to p5.js reference added
processing/p5.js pull request #6890
Opened 2024-03-18 18:59 UTC by Surbhi-Pittie

Changes:
Hindi translation file for contributing to p5.js reference page added

#### PR Checklist

- [x] `npm run lint` passes
- [x] [Inline documentation] is included / updated
- [x] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2024-03-18 19:00 UTC, Surbhi-Pittie commented
@Divyansh013 @TanviKumar PTAL

2024-03-20 14:31 UTC, Divyansh013 requested changes
Hi @Surbhi-Pittie have left some reviews, please look into this asap

2024-03-20 14:31 UTC, Divyansh013 commented on contributor_docs/hi/contributing_to_the_p5.js_reference.md
> + * <a href="#/p5/angleMode">angleMode</a>.
translate description before this anchor tag

2024-03-20 14:31 UTC, Divyansh013 commented on contributor_docs/hi/contributing_to_the_p5.js_reference.md
> +इस तरह के ब्लॉक में कोई भी चीज संदर्भ दस्तावेज़ के रूप में निर्वाचित की जाएगी। आप इस कोड टिप्पणियों के इस स्टाइल के माध्यम से परिचित हो सकते हैं [JSDoc](https://jsdoc.app/) के माध्यम से। p5.js न JSDo
we can remove "न" and can add comma

2024-03-20 14:31 UTC, Divyansh013 commented on contributor_docs/hi/contributing_to_the_p5.js_reference.md
> + *
we can translate this part too

2024-03-20 14:31 UTC, Divyansh013 commented on contributor_docs/hi/contributing_to_the_p5.js_reference.md
> + * also determine output formatting such as when
translate the part above anchor tag

2024-03-21 08:05 UTC, TanviKumar approved these changes

2024-03-21 20:42 UTC, merged

2024-03-21 20:43 UTC, Qianqianye commented
Looks great, thanks @Surbhi-Pittie @Divyansh013 @TanviKumar 💖
@all-contributors please add @Surbhi-Pittie for translation