Update access.md
processing/p5.js pull request #6945
Opened 2024-04-07 16:39 UTC by Harrycheng233

Resolves #[Add issue number here]

 Changes:

 Screenshots of the change:

#### PR Checklist

- [ ] `npm run lint` passes
- [ ] [Inline documentation] is included / updated
- [ ] [Unit tests] are included / updated

[Inline documentation]: https://github.com/processing/p5.js/blob/main/contributor_docs/inline_documentation.md
[Unit tests]: https://github.com/processing/p5.js/tree/main/contributor_docs#unit-tests

2024-04-07 22:59 UTC, sproutleaf requested changes
谢谢！

2024-04-07 22:59 UTC, sproutleaf commented on contributor_docs/zh/access.md
> +# 我们关注的重点是可及性
我觉得Access应该翻译成可访问性或网页无障碍？@unicar9 你觉得呢？

2024-04-07 22:59 UTC, sproutleaf commented on contributor_docs/zh/access.md
> +# 我们关注的重点是可及性
哦哦哦等下 我看到下文写的access (inclusion and accessibility)了 看来无障碍性accessibility和access还是得区分开 还是等unicar的意见哦！

2024-04-07 22:59 UTC, sproutleaf commented on contributor_docs/zh/access.md
> +在[ 2019 年贡献者大会](https://p5js.org/community/contributors-conference-2019.html)上，我们承诺只向 p5.js 添加提高可及性（包括包容性和无障碍性）的功能。我们不会接受那些不支持这些努力的功能请求。我们致力于认知、消除和预防障碍的工作。这意味着要考虑在交叉[^1]体验中可能影响可及性和参与度的多样性方向。这包括了性别、种族
认知、消除->承认、废除

2024-04-07 22:59 UTC, sproutleaf commented on contributor_docs/zh/access.md
> +- 举办社区活动（例如，[ p5.js 访问日2022](https://p5js.org/community/p5js-access-day-2022.html)，[我们想要的网络：p5.js x W3C TPAC 2020](https://medium.com/processing-foundation/p5-js-x-w3c-tpac-bee4c621a053)），采用以可及为中心的组织
感觉可以把p5.js访问日中的访问换成access的翻译，和上文同步！

2024-04-07 22:59 UTC, sproutleaf commented on contributor_docs/zh/access.md
> +这个版本的 p5.js 可及性声明是在2023年开源艺术贡献者大会上，与 Evelyn Masso、Nat Decker、Bobby Joe Smith III、Sammie Veeler、Sonia (Suhyun) Choi、Xin Xin、Kate Hollenbach、Lauren Lee McCarthy、Caroline Sinders、Qianqian Ye、Tristan Jov
Processing Foundation不用翻译！另外这里fellowship可以翻译成研究奖金

2024-04-08 02:42 UTC, Harrycheng233 commented on contributor_docs/zh/access.md
> +- 举办社区活动（例如，[ p5.js 访问日2022](https://p5js.org/community/p5js-access-day-2022.html)，[我们想要的网络：p5.js x W3C TPAC 2020](https://medium.com/processing-foundation/p5-js-x-w3c-tpac-bee4c621a053)），采用以可及为中心的组织
我把它翻译成了“无障碍日”，因为如果直接翻译成“可及日”或“可及性日”听起来有点别扭？（虽然没有和别的翻译统一，但如果有更倾向的word choice的话我及时修改！）

2024-04-08 02:42 UTC, Harrycheng233 commented on contributor_docs/zh/access.md
> +在[ 2019 年贡献者大会](https://p5js.org/community/contributors-conference-2019.html)上，我们承诺只向 p5.js 添加提高可及性（包括包容性和无障碍性）的功能。我们不会接受那些不支持这些努力的功能请求。我们致力于认知、消除和预防障碍的工作。这意味着要考虑在交叉[^1]体验中可能影响可及性和参与度的多样性方向。这包括了性别、种族
好滴！

2024-04-08 08:06 UTC, unicar9 commented on contributor_docs/zh/access.md
> +增加可及性并不专注于扩大 p5.js 社区的人数。它是一种持续的承诺，旨在使 p5.js 对因结构性压迫而被排除在 p5.js 社区外的人们更加可用和易于接触。这一承诺扩展到 p5.js 提供的工具和平台。它还包括 p5.js 领导层的组成、决策和行动。我们反对技术文化中对速度、增长和竞争的追求。我们将有意识、缓慢、适应性和负责任作为集体关爱的行动优先考虑。
我们将有意识、缓慢、适应性和负责任作为集体关爱的行动优先考虑。-> 我们将致力于推行以下互相关照的集体行为：深思熟虑、放慢步调、互相照应和积极负责。（稍微意译让中文更通顺自然。）

2024-04-08 08:18 UTC, unicar9 commented on contributor_docs/zh/access.md
> +在[ 2019 年贡献者大会](https://p5js.org/community/contributors-conference-2019.html)上，我们承诺只向 p5.js 添加提高可及性（包括包容性和无障碍性）的功能。我们不会接受那些不支持这些努力的功能请求。我们致力于承认、废除和预防障碍的工作。这意味着要考虑在交叉[^1]体验中可能影响可及性和参与度的多样性方向。这包括了性别、种族
我们致力于承认、废除和预防障碍的工作。-> 我们致力于识别、消除和预防与可及性相关的障碍。

2024-04-09 18:09 UTC, sproutleaf approved these changes

2024-04-09 21:27 UTC, unicar9 approved these changes

2024-04-09 22:40 UTC, sproutleaf approved these changes
Approve. Tagging @Qianqianye @limzykenneth for merging. Thank you!

2024-04-10 11:09 UTC, limzykenneth commented
@Harrycheng233 @unicar9 @sproutleaf There's a merge conflict here, please do have a look. Thanks.

2024-04-10 17:25 UTC, sproutleaf commented
> @Harrycheng233 @unicar9 @sproutleaf There's a merge conflict here, please do have a look. Thanks.

@Harrycheng233 is unable to resolve the conflicts (error message below). Would it be better to delete the existing file and push a new file in 2 separate PRs?
![complex](https://github.com/processing/p5.js/assets/116130954/6f6a2a87-8b32-43f7-b92e-745a68a48e8b)

2024-04-11 12:58 UTC, limzykenneth commented
@sproutleaf I think I know what's up here, I changed the language code used in this repo from `zh` to `zh-Hans` which likely caused the conflict here with git not able to find the file being changed in this PR. I can resolve this and merge, no worries.

2024-04-12 17:53 UTC, merged