Adds `webp` mime type to `saveCanvas`.
processing/p5.js pull request #7140
Opened 2024-07-19 16:32 UTC by starzonmyarmz

Updates source code to properly support `webp` format. Refs https://github.com/processing/p5.js-website/pull/451.

2024-07-20 12:47 UTC, nickmcintyre requested changes
Great start @starzonmyarmz! Would you please also add `'wepb'` to the main reference text on line 165?

2024-07-22 12:11 UTC, starzonmyarmz commented
Thanks @nickmcintyre. Fixed in https://github.com/processing/p5.js/pull/7140/commits/bec4f75eaffd0c846b7b23a35f6f9e9b58627554.

2024-07-22 14:12 UTC, nickmcintyre approved these changes
Looks good to me–thanks @starzonmyarmz!

2024-07-22 19:58 UTC, merged

2024-07-22 19:59 UTC, Qianqianye commented
Thank you both!
@all-contributors please add @starzonmyarmz for documentation